---
- hosts: db
  become: true
  gather_facts: false

  tasks:
   - name: to update repo
     raw: apt-get update
   - name: to install mysql server
     apt: name=mysql-server update_cache=yes state=present
   - name: to start mysql server
     service: name=mysql  state=started 

