---
- hosts: web
  become: true
  gather_facts: false

  tasks:
    - name: to update repo
      raw: apt-get update
    - name: to install apache2 
      apt: name=apache2 update_cache=yes state=present
    - name: to install apache2
      service: name=apache2 state=started

